---


- name: pm2 stop
  become: true
  command: "pm2 stop default"
  ignore_errors: True 

#Pretty sure I'm missing the part where actually install the udapeople app!
- name: create application directory
  file:
    path: /home/ubuntu/application
    state: directory 

- name: copy from local to remote and unpack on remote server
  become: true
  unarchive:
    copy: true
    src: artifact.tar.gz
    dest: /home/ubuntu/application
    owner: ubuntu


#For some reason npm install didnt' succeed
# but connect to box.  change to /home/ununtu/application
# npm install
# pm2 start npm -- start
# and it worked!
# Did it fail because directory not correct?

# - name: "npm install"
#   become: true
#   command: "npm install"

#Maybe try this...
- name: "npm install"
  become: true
  shell: |
      cd /home/ununtu/application
      npm install


#Not sure if need this?
# - name: start node app
#   shell: |
#     cd ~/application/dist
#     pm2 start main.js



- name: pm2 start
  become: true
  command: "pm2 start npm -- start"
  #ignore_errors: True 

#npm install ALREADY DONE??
#pm2 stop default
#pm2 start npm -- start

