---
- name: create application directory
  file:
    path: /home/ubuntu/application
    state: directory 

- name: copy from local to remote and unpack on remote server
  become: true
  unarchive:
    copy: true
    src: artifact.tar.gz
    dest: /home/ubuntu/application
    owner: ubuntu


#For some reason npm install didnt' succeed
# but connect to box.  change to /home/ununtu/application
# npm install
# pm2 start npm -- start
# and it worked!
# Did it fail because directory not correct?

# - name: "npm install"
#   become: true
#   command: "npm install"

- name: "npm install"
  become: true
  shell: |
      cd /home/ubuntu/application
      npm install

# - name: pm2 stop
#   become: true
#   command: "pm2 stop default"
#   ignore_errors: True 

- name: pm2 stop
  become: true
  shell: |
    cd /home/ubuntu/application
    pm2 stop default
  ignore_errors: True 


# - name: pm2 start
#   become: true
#   command: "pm2 start npm -- start"
  #ignore_errors: True 

- name: pm2 start
  become: true
  shell: |
    cd /home/ubuntu/application
    pm2 start npm -- start
    
#   command: "pm2 start npm -- start"



