---

- name: pm2 stop
  become: true
  command: "pm2 stop default"
  ignore_errors: True 

- name: pm2 start
  become: true
  command: "pm2 start npm -- start"
  #ignore_errors: True 

#npm install ALREADY DONE??
#pm2 stop default
#pm2 start npm -- start